export function persistJournalImage(sourceUri: string, suggestedName?: string | null): Promise<string>;
export function persistJournalImageBase64(dataBase64: string, extension?: string): Promise<string>;
export function persistJournalImageBytes(data: Uint8Array, extension?: string): Promise<string>;
export function persistJournalThumbnail(sourceUri: string): Promise<string>;
export function getJournalStorageBreakdown(): { original: { files: number; bytes: number }; thumbnails: { files: number; bytes: number }; totalBytes: number };
export function clearJournalThumbnailFiles(): { files: number; bytes: number };
export function deleteJournalImage(uri: string): void;
export type JournalMediaStorageUsage = { files: number; bytes: number };
export type JournalMediaCleanupResult = JournalMediaStorageUsage & { deletedFiles: number; freedBytes: number };
export function getJournalMediaStorageUsage(): Promise<JournalMediaStorageUsage>;
export function cleanupUnusedJournalMedia(referencedUris: string[], gracePeriodMs?: number): Promise<JournalMediaCleanupResult>;
